# This is a basic workflow to help you get started with Actions

name: Deploy to amazon ec2 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the dev branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  backend:
    # The type of runner that the job will run on
    name: CI with gradle
    runs-on: ubuntu-18.04
    defaults: 
      run:  
        shell: bash 
        working-directory: study-app-server
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: action checkout 
        uses: actions/checkout@v2
        
      - name: gradle build 
        run: ./gradlew build -x test       
        
  front:
    name: CI with node.js 
    runs-on: ubuntu-latest 
    defaults: 
      run:
        shell: bash 
        working-directory: study-app 
    
    steps: 
      - name: action checkout 
        uses: actions/checkout@v2 
        
      - name: front build 
        run: npm run build 
          
    
    
     
    
